### ISSUE TITLE
Problems to load babelsberg-s

### ISSUE THREAD

**Issue by no-e-in** [babelsberg/babelsberg-s#2]
A new Squeak4.5-13680.image on windows7 64

![problem](https://cloud.githubusercontent.com/assets/11634455/8376512/76006474-1c08-11e5-8261-665fb86a5c2e.jpg)

**Comment by timfel** [comment]
Can you check your github-cache folder (should be next to the image). If the Babelsberg folder hierarchy is empty (`github-cache\babelsberg#babelsberg-s\master` but then nothing), then you're hitting a known issue with Metacello on Windows

**Comment by timfel** [comment]
If you are just looking to try it out, we have prebuilt images here: http://www.lively-kernel.org/babelsberg/BabelsbergS/

**Comment by no-e-in** [comment]
Yes, Babelsberg folder hierarchy is empty.

**Comment by timfel** [comment]
May I ask for what you wanted to try it?

**Comment by no-e-in** [comment]
[Curiosity](http://astares.blogspot.it/2015/06/babelsbergs.html).
A few years ago I read of [ThingLab](https://en.wikipedia.org/wiki/ThingLab).
